name: CI - Unit and System Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  unit-tests:
    name: Unit tests (Battery)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-describe pytest-spec pytest-mock

      - name: Run unit tests
        run: |
          pytest -q --maxfail=1 --disable-warnings

  system-tests:
    name: System tests (myDB)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-describe pytest-spec pytest-mock
          # Add app/system deps here, e.g. databases, clients
          # pip install -r requirements.txt

      - name: Prepare environment
        run: |
          # Example: create temp directories, set env vars, etc.
          echo "SYSTEM_TEST_ENV=ci" >> $GITHUB_ENV

      - name: Run system tests
        env:
          SYSTEM_TEST_ENV: ${{ env.SYSTEM_TEST_ENV }}
        run: |
          # Limit to system tests directory, if you separate them
          pytest -q tests/system --maxfail=1 --disable-warnings
